/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as ChallengesWindowResizerRouteImport } from './routes/challenges/window-resizer'
import { Route as ChallengesToggleThemeRouteImport } from './routes/challenges/toggle-theme'
import { Route as ChallengesTodoListRouteImport } from './routes/challenges/todo-list'
import { Route as ChallengesTimerRouteImport } from './routes/challenges/timer'
import { Route as ChallengesSearchRouteImport } from './routes/challenges/search'
import { Route as ChallengesFetchUsersRouteImport } from './routes/challenges/fetch-users'
import { Route as ChallengesCounterRouteImport } from './routes/challenges/counter'
import { Route as ChallengesControlledInputRouteImport } from './routes/challenges/controlled-input'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesWindowResizerRoute = ChallengesWindowResizerRouteImport.update({
  id: '/challenges/window-resizer',
  path: '/challenges/window-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesToggleThemeRoute = ChallengesToggleThemeRouteImport.update({
  id: '/challenges/toggle-theme',
  path: '/challenges/toggle-theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesTodoListRoute = ChallengesTodoListRouteImport.update({
  id: '/challenges/todo-list',
  path: '/challenges/todo-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesTimerRoute = ChallengesTimerRouteImport.update({
  id: '/challenges/timer',
  path: '/challenges/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSearchRoute = ChallengesSearchRouteImport.update({
  id: '/challenges/search',
  path: '/challenges/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesFetchUsersRoute = ChallengesFetchUsersRouteImport.update({
  id: '/challenges/fetch-users',
  path: '/challenges/fetch-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesCounterRoute = ChallengesCounterRouteImport.update({
  id: '/challenges/counter',
  path: '/challenges/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesControlledInputRoute =
  ChallengesControlledInputRouteImport.update({
    id: '/challenges/controlled-input',
    path: '/challenges/controlled-input',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges/controlled-input': typeof ChallengesControlledInputRoute
  '/challenges/counter': typeof ChallengesCounterRoute
  '/challenges/fetch-users': typeof ChallengesFetchUsersRoute
  '/challenges/search': typeof ChallengesSearchRoute
  '/challenges/timer': typeof ChallengesTimerRoute
  '/challenges/todo-list': typeof ChallengesTodoListRoute
  '/challenges/toggle-theme': typeof ChallengesToggleThemeRoute
  '/challenges/window-resizer': typeof ChallengesWindowResizerRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges/controlled-input': typeof ChallengesControlledInputRoute
  '/challenges/counter': typeof ChallengesCounterRoute
  '/challenges/fetch-users': typeof ChallengesFetchUsersRoute
  '/challenges/search': typeof ChallengesSearchRoute
  '/challenges/timer': typeof ChallengesTimerRoute
  '/challenges/todo-list': typeof ChallengesTodoListRoute
  '/challenges/toggle-theme': typeof ChallengesToggleThemeRoute
  '/challenges/window-resizer': typeof ChallengesWindowResizerRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges/controlled-input': typeof ChallengesControlledInputRoute
  '/challenges/counter': typeof ChallengesCounterRoute
  '/challenges/fetch-users': typeof ChallengesFetchUsersRoute
  '/challenges/search': typeof ChallengesSearchRoute
  '/challenges/timer': typeof ChallengesTimerRoute
  '/challenges/todo-list': typeof ChallengesTodoListRoute
  '/challenges/toggle-theme': typeof ChallengesToggleThemeRoute
  '/challenges/window-resizer': typeof ChallengesWindowResizerRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges/controlled-input'
    | '/challenges/counter'
    | '/challenges/fetch-users'
    | '/challenges/search'
    | '/challenges/timer'
    | '/challenges/todo-list'
    | '/challenges/toggle-theme'
    | '/challenges/window-resizer'
    | '/challenges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges/controlled-input'
    | '/challenges/counter'
    | '/challenges/fetch-users'
    | '/challenges/search'
    | '/challenges/timer'
    | '/challenges/todo-list'
    | '/challenges/toggle-theme'
    | '/challenges/window-resizer'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/challenges/controlled-input'
    | '/challenges/counter'
    | '/challenges/fetch-users'
    | '/challenges/search'
    | '/challenges/timer'
    | '/challenges/todo-list'
    | '/challenges/toggle-theme'
    | '/challenges/window-resizer'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesControlledInputRoute: typeof ChallengesControlledInputRoute
  ChallengesCounterRoute: typeof ChallengesCounterRoute
  ChallengesFetchUsersRoute: typeof ChallengesFetchUsersRoute
  ChallengesSearchRoute: typeof ChallengesSearchRoute
  ChallengesTimerRoute: typeof ChallengesTimerRoute
  ChallengesTodoListRoute: typeof ChallengesTodoListRoute
  ChallengesToggleThemeRoute: typeof ChallengesToggleThemeRoute
  ChallengesWindowResizerRoute: typeof ChallengesWindowResizerRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/window-resizer': {
      id: '/challenges/window-resizer'
      path: '/challenges/window-resizer'
      fullPath: '/challenges/window-resizer'
      preLoaderRoute: typeof ChallengesWindowResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/toggle-theme': {
      id: '/challenges/toggle-theme'
      path: '/challenges/toggle-theme'
      fullPath: '/challenges/toggle-theme'
      preLoaderRoute: typeof ChallengesToggleThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/todo-list': {
      id: '/challenges/todo-list'
      path: '/challenges/todo-list'
      fullPath: '/challenges/todo-list'
      preLoaderRoute: typeof ChallengesTodoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/timer': {
      id: '/challenges/timer'
      path: '/challenges/timer'
      fullPath: '/challenges/timer'
      preLoaderRoute: typeof ChallengesTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/search': {
      id: '/challenges/search'
      path: '/challenges/search'
      fullPath: '/challenges/search'
      preLoaderRoute: typeof ChallengesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/fetch-users': {
      id: '/challenges/fetch-users'
      path: '/challenges/fetch-users'
      fullPath: '/challenges/fetch-users'
      preLoaderRoute: typeof ChallengesFetchUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/counter': {
      id: '/challenges/counter'
      path: '/challenges/counter'
      fullPath: '/challenges/counter'
      preLoaderRoute: typeof ChallengesCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/controlled-input': {
      id: '/challenges/controlled-input'
      path: '/challenges/controlled-input'
      fullPath: '/challenges/controlled-input'
      preLoaderRoute: typeof ChallengesControlledInputRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesControlledInputRoute: ChallengesControlledInputRoute,
  ChallengesCounterRoute: ChallengesCounterRoute,
  ChallengesFetchUsersRoute: ChallengesFetchUsersRoute,
  ChallengesSearchRoute: ChallengesSearchRoute,
  ChallengesTimerRoute: ChallengesTimerRoute,
  ChallengesTodoListRoute: ChallengesTodoListRoute,
  ChallengesToggleThemeRoute: ChallengesToggleThemeRoute,
  ChallengesWindowResizerRoute: ChallengesWindowResizerRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
